### ISSUE TITLE
✨ Compliments 🌟

### ISSUE THREAD

**Issue by duckRabbitPy** [fac-23/trip-planner#38]
## Great job! Looking forward to final product

+ Great explorative approach, using new libraries such as uuid, pdf viewer and indexDB, going out of your comfort zone. 🗺
+ Clear instructions 🙉
+ Good use of native date picker ⏰
+ Styled components 💅
+ It's very cool that multiple file types are supported 😎

**Comment by miahbates** [comment]
Great use of use effect to manage state! ✨

**Comment by julietteorpen** [comment]
Great look and so cool that you can view the docs you've stored locally 🌟 🤩

**Comment by reubengt** [comment]
loving the comments and overall readability of the codebase!
